from tkinter import *
window=Tk()
def test():
    lb.config(text=var.get())
window.geometry("400x400")
window.config(bg="blue")
window.attributes('-toolwindow',0.7)
var=StringVar()
cb1=Checkbutton(window,text="python",font=("Time New Roman",30,"bold"),onvalue="Your choice is Python",offvalue="Select from the choice",variable=var,command=test)
cb1.deselect()
cb1.pack()
cb2=Checkbutton(window,text="java",font=("Time New Roman",30,"bold"),onvalue="Your choice is Java",variable=var,command=test)
cb2.deselect()
cb2.pack()
lb=Label(window,text="",font=("Time New Roman",30,"bold"),bg="blue")
lb.pack()
#bt=Button(window,text="press",font=30,command=test,relief="groove")
#bt.pack()
window.mainloop()